name: Update JSON from Google Sheets

on:
  schedule:
    - cron: "*/5 * * * *"   # update setiap 5 menit
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Fetch JSON from Google Sheets
        run: |
          curl -s "https://script.google.com/macros/s/AKfycbzrcEZ_sVRampsW1EKf_AS7Egg2OYR8UJPBYgSgwDm9uSXKJ0XCw1sVN6iAyfwmXfw/exec" -o data.json

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json
          git commit -m "Update data.json"
          git push
